# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Checkout 🛎️
      #  uses: actions/checkout@v2
      #  with:
      #    submodules: true
      #    lfs: true
                
      #- name: Cache scummvm 
      #  uses: actions/cache@v2
      #  with:
      #    path: ./scummvm
      #    key: scummvm

      - name: Checkout icons 🛎️
        uses: actions/checkout@v2
        with:
         repository: scummvm/scummvm-icons
         path: scummvm-icons

      - name: Build ScummVM icons 🔧
        run: |
          cd scummvm-icons
          python3 gen-set.py
          cd ..

      - name: Build ScummVM 🔧
        run: |
          git clone https://github.com/neuromancer/scummvm-demo --recursive 
          cd scummvm
          git checkout emscripten
          git pull
          git remote add upstream https://github.com/scummvm/scummvm.git
          git fetch upstream
          git rebase upstream/master
          cp ../scummvm-icons/gui-icons-*.dat ./gui/themes/gui-icons.dat
          ./dists/emscripten/build.sh build --verbose  --enable-plugins --disable-tinygl --disable-all-engines --enable-engine-static=hypno --bundle-games=sinistersix,"https://downloads.scummvm.org/frs/demos/hypno/wetlands-dos-demo1-en.zip","https://downloads.scummvm.org/frs/demos/hypno/wetlands-dos-demo2-en.zip"
          cp build-emscripten/scummvm.html build-emscripten/index.html
          cd ..

      - name: Deploy Demo 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: scummvm/build-emscripten # The folder the action should deploy.
