# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: true
 
      - name: Checkout and build ScummVM icons 🔧
        run: |
          git clone https://github.com/scummvm/scummvm-icons
          cd scummvm-icons
          python3 gen-set.py
          cd ..

      - name: Rebase ScummVM 🔧
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone https://github.com/chkuendig/scummvm -b emscripten --recursive scummvm-to-rebase
          cd scummvm-to-rebase
          git remote add upstream https://github.com/scummvm/scummvm.git
          git fetch upstream
          git rebase upstream/master

      - name: Restore ScummVM cache
        uses: actions/cache@v2
        with:
          path: |
            ./scummvm-to-rebase/engines/engines.awk
            ./scummvm-to-rebase/engines/detection_table.h
            ./scummvm-to-rebase/engines/plugins_table.h
            ./scummvm-to-rebase/config.h
            ./scummvm-to-rebase/config.mk
            ./scummvm-to-rebase/configure.stamp
            ./scummvm-to-rebase/dists/emscripten/emsdk-3.1.6
            ./scummvm-to-rebase/dists/emscripten/libs 
            ./scummvm-to-rebase/**/*.[o,a]
            ./scummvm-to-rebase/**/**/*.[o,a]
            ./scummvm-to-rebase/**/**/**/*.[o,a]
            ./scummvm-to-rebase/**/**/**/**/*.[o,a]
            ./scummvm-to-rebase/**/**/**/**/**/*.[o,a]
            ./scummvm-to-rebase/**/**/**/**/**/**/*.[o,a]
          key: scummvm-cache

      - name: Build ScummVM
        run: |
          cd scummvm-to-rebase
          cp ../scummvm-icons/gui-icons-*.dat ./gui/themes/gui-icons.dat
          ./dists/emscripten/build.sh build --verbose --enable-optimizations --enable-plugins --disable-tinygl --disable-all-engines --enable-engine-dynamic=private --enable-engine-dynamic=hypno --bundle-games=sinistersix,"https://downloads.scummvm.org/frs/demos/hypno/wetlands-dos-ni-demo-en.zip","https://downloads.scummvm.org/frs/demos/hypno/wetlands-dos-demo1-en.zip","https://downloads.scummvm.org/frs/demos/hypno/wetlands-dos-demo2-en.zip","https://downloads.scummvm.org/frs/demos/private/private-eye-demo-en.zip","https://downloads.scummvm.org/frs/demos/private/private-eye-demo-es.zip",


          cd ..
          cp -R scummvm-to-rebase/build-emscripten scummvm

      - name: Deploy Demo 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: main # The branch the action should deploy to.
          repository-name: neuromancer/neuromancer.github.io
          token: ${{ secrets.PAT }} 
          folder: scummvm/build-emscripten # The folder the action should deploy.
